name: Manage GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - create
          - update
          - delete
      secret_name:
        description: 'Secret name'
        required: true
        type: string
      secret_value:
        description: 'Secret value (for create/update)'
        required: false
        type: string

jobs:
  manage-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      secrets: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Manage GitHub Secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: ${{ github.event.inputs.secret_name }}
          value: ${{ github.event.inputs.secret_value }}
          pa_token: ${{ secrets.GITHUB_TOKEN }}
          
        if: github.event.inputs.action != 'delete'
        
      # Note: Deletion requires different action or API call
      - name: Delete secret (if requested)
        if: github.event.inputs.action == 'delete'
        run: |
          echo "Secret deletion requires GitHub API call with proper permissions"
          # You would need to use GitHub CLI or API here with a PAT that has admin:repo permissions
